apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccount: sa-test-1
      containers:
      - name: do-webapp
        image: amitsaha/webapp-demo:python-django
        ports:
        - containerPort: 8000
