apiVersion: v1
kind: Namespace
metadata:
  name: service1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service1
  namespace: service1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      serviceAccount: service1
      containers:
      - name: app
        image: amitsaha/k8s-sa-volume-demo-service1:sa
        env:
        - name: LISTEN_ADDR
          value: ":8080"
        - name: SERVICE2_CONNSTRING
          value: "http://app.service2.svc.cluster.local"
        ports:
        - containerPort: 8080
