apiVersion: v1
kind: Namespace
metadata:
  name: service2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service2
  namespace: service2
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: service2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: service2
  namespace: service2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      serviceAccount: service2
      containers:
      - name: app
        image: amitsaha/k8s-sa-volume-demo-service2:sa
        env:
        - name: LISTEN_ADDR
          value: ":8081"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app 
  namespace: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

