apiVersion: v1
kind: Namespace
metadata:
  name: service1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service1
  namespace: service1
---
apiVersion: v1
kind: Deployment 
metadata:
  name: app
  namespace: service1
spec:
  template:
    spec:
      containers:
      - image: amitsaha/learnk8s-sa-service1
      name: learnk8s-sa-service1
      volumeMounts:
      - mountPath: /var/run/secrets/tokens
        name: identity
      serviceAccountName: service1
      volumes:
      - name: identity
      projected:
        sources:
        - serviceAccountToken:
            path: identity
            expirationSeconds: 3600
            audience: service2
