apiVersion: v1
kind: Namespace
metadata:
  name: secret-store
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-store
  namespace: secret-store
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: secret-store
  namespace: secret-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: secret-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-store
  template:
    metadata:
      labels:
        app: secret-store
    spec:
      serviceAccount: secret-store
      containers:
      - name: app
        image: amitsaha/k8s-sa-volume-demo-ss:sa-2
        env:
        - name: LISTEN_ADDR
          value: ":8081"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app 
  namespace: secret-store
spec:
  selector:
    app: secret-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

